# Generated by Django 5.2.8 on 2026-05-19 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for account in Account.objects.all().iterator():
        UserProfile.objects.get_or_create(user_id=account.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_admin_log_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
