# Generated by Django 5.2.8 on 2026-05-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_product_slug'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.vendor'),
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('uses', 'Uses'), ('dosage', 'Dosage'), ('side_effects', 'Side Effects'), ('warnings', 'Warnings'), ('precautions', 'Precautions'), ('interactions', 'Interactions'), ('storage', 'Storage'), ('quick_tips', 'Quick Tips'), ('faq', 'FAQs'), ('lifestyle', 'Lifestyle Recommendation')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('product_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Home.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='Home.productcontent')),
            ],
        ),
    ]
